language: node_js

cache:
  directories:
    - ~/.npm

notifications:
  email: false

node_js:
  - '10'

jobs:
  include:
    - stage: release
      node_js: 10
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm install
          - npx semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
